### ISSUE TITLE
New Change to Security List and Network Security Group

### ISSUE THREAD

**Issue by anilbhagavatula** [KsiriCreations/oci-auditing#23]
- [x] in security list can we add one more columns for the report which SL belongs to public or private
       - the logic used is for any wide open rule we have raised the risk as critical with red
- [x] one change which strikes me is we can put high critical only if wide open rule 0.0.0.0/0 is for public subnet SL
       - and for any SL associated with private subnet we can put the risk level as medium
- [ ] we can implement same to NSG also

**Comment by kk-hiraskar** [comment]
@anilbhagavatula
please confirm if my understanding below is correct:
* Any accessible "Security List" can be created/added to "Subnet" that we have access
* Means same "Security List" can be added to either a Private or Public "Subnet" ???

> * We are showing Subnets, & SLs in separate tabs as of now.
> * So is it really possible to consider Subnet's access level in to SLs for auditing with our current structure ?
> * if really we need to consider do we need to change in any way, current reporting structure ?

### Current highlights:
![image](https://user-images.githubusercontent.com/19647561/115056441-7cf24280-9f00-11eb-81f3-ca6d46baa344.png)
same also mentioned in document: https://github.com/KsiriCreations/oci-auditing#network-security-groups

**Comment by sirieebr** [comment]
May this suggestion be helpful..
- [ ] in subnet listing, add a privacy column which says if it's public or private
- [ ] for security list and NSG, check if it's any subnet is public, then apply public rule else private.
- [ ] also make sure to show it's subnets

**Comment by kk-hiraskar** [comment]
@anilbhagavatula, based on previous comment suggestions from @sirieebr questions are resolved and proceeding for implementations:
* for SecurityList, one more column added **`Subnet's Privacy`**
  _* as security list itself not having any privacy to decide the risk, now I am considering the privacy from it's parent kind of Subnet/s._
* based on this privacy, for 0.0.0.0/0 risk is now reduced to Medium if its private

> Note: Release still pending, let me know if required now, else I will combine it later.

**Comment by kk-hiraskar** [comment]
Closing this now, and similar update to NSG will be tracked via #27
