### ISSUE TITLE
Translate docs to PT-BR and Spanish

### ISSUE THREAD

**Issue by valdecircarvalho** [KsiriCreations/oci-auditing#30]
Hello! 
I would like to translate the documentation to Brazilian Portuguese and Spanish if it´s ok to you.

**Comment by kk-hiraskar** [comment]
Sure @valdecircarvalho , I will be happy for that.

I have created a structure for both the languages.
```
doc/lang-es
doc/lang-pt-br 
```
I have copied main Readme files into these 2,  
if you wish to translate the sub pages in `doc/*.md`, you can also take a copy of that inside language folders.  

Once docs are ready, we can also create a link for main "Readme" referring to pt-br & es

Thanks & Regards,
KK

**Comment by valdecircarvalho** [comment]
Thanks! I will make it available by the end of this week right? Very busy here.

**Comment by kk-hiraskar** [comment]
Hi @valdecircarvalho 
I have added language translations in to main document itself, request you to review this feature.
https://github.com/KsiriCreations/oci-auditing#read-this-in-other-language

**Comment by kk-hiraskar** [comment]
Auto translations to many languages now available on main doc itself. https://github.com/KsiriCreations/oci-auditing#read-this-in-other-language

If automatic translations are not so flexible to read, then please reopen this issue.
Thanks.
