### ISSUE TITLE
Feature Request: Need to audit the child region cloud guard problem and risks

### ISSUE THREAD

**Issue by Kakumkum** [KsiriCreations/oci-auditing#31]
Karthikeyan Kumar  3:44 PM
Tool pulled the cloud guard home region only
But I enabled cloud in child region london

Karthik:  3:45 PM
Wow.. you stepped in to log.. That's nice..

Karthikeyan Kumar  3:45 PM
Yeah

Karthik:  3:46 PM
so do you wish to enable on home, and get report..
or if you want to get only for other selected regions, then I will think of updating the tool itself..

Karthikeyan Kumar  3:47 PM
I want only to get the report on selected region
Can you give the option in tool under cloud guard section - > choose the regions

Karthik:  3:48 PM
Hmm, I will provide an option, on which selection, it will traverse through all regions and tries to get report..

Karthikeyan Kumar  3:49 PM
ok great

Karthik: 3:49 PM
just thinking in generic way :-)

Karthikeyan Kumar  3:49 PM
👍 

Karthik:  3:50 PM
ok.. would you like to create a ChangeRequest on github, or shall I create on your behalf ?

Karthikeyan Kumar  3:50 PM
No issues , I can create the CR
Ca you give the link

Karthik: 3:51 PM
Ok that's great..
from tool, `Help > Submit > New feature`
on that page u can enter our discussion, and submit..

Karthikeyan Kumar  3:55 PM
Sure, thanks

**Comment by kk-hiraskar** [comment]
## Understanding for this feature update:
1. when CG enabled on root compartment, then all regions issue will be consolidated and shown 
2. if CG enabled only for specific compartments in regions, then need to loop through querying all regions

**Comment by kk-hiraskar** [comment]
### How to scan through all the others, when CG not enabled on root compartment
> adding this key to config will force tool to scan through all regions and compartments.
> `scan_all_regions=x`

feature added in release: 3.7.8
get new version from releases, or directly tool menu `Help > Check Updates`
