### ISSUE TITLE
Issue while fetching the child compartment resource details 

### ISSUE THREAD

**Issue by erankiraghavendra** [KsiriCreations/oci-auditing#6]
Hi Karthik, 

As discussed, when we're planning to fetch the details of the child compartment resource we're facing issues. Can you please cross check and do let me know. 

Thanks,
Raghavendra Eranki

**Comment by kk-hiraskar** [comment]
Additional Details:
NSG linked to VCN can exist in any other compartment at any level.

After checking in to the flow, currently NSGs are scanned for only compartments where at least an VCN exists, this was implemented as an optimization factor.

However this optimization may work for other components like Security Lists, but not for NSG.

Considering this issue for the fixes.

**Comment by kk-hiraskar** [comment]
@erankiraghavendra 
issues fixed in https://github.com/KsiriCreations/oci-auditing/releases/tag/3.6.6

Please re-check the scenario and update.

**Comment by kk-hiraskar** [comment]
Thanks @erankiraghavendra for confirming the issue-fix in [v3.6.6](https://github.com/KsiriCreations/oci-auditing/releases/tag/3.6.6)

For other improvements discussed, like NSG & VCN names to show
[Issue #7](https://github.com/KsiriCreations/oci-auditing/issues/7) is updated.
