### ISSUE TITLE
Displaying the public IP and memeory of the instance 

### ISSUE THREAD

**Issue by erankiraghavendra** [KsiriCreations/oci-auditing#9]
Hi Karthik, 
As discussed, can you please display the public IP/private IP and memory of the instances. 
Thanks,
Raghavendra Eranki

**Comment by kk-hiraskar** [comment]
**Sorry Raghavendra,**
update by tomorrow is not possible :-(
IPs are not directly linked to instances, it is like via vinics & network components etc.,

please get it manually for now..
I will analyze this & try to implement.. Thanks for your suggestions..

Developer Self Note:
https://github.com/oracle/oci-python-sdk/blob/master/examples/get_all_instance_ip_addresses_and_dns_info.py 
computeCl.list_instances > computeCl.list_vnic_attachments > link instances & vnics with hashes > and many more things to be done

**Comment by kk-hiraskar** [comment]
implemented to show private & public IPs, and also RAM memory in ver3.6.11.

Note: you need to add this config line to get additional information of IPs
```
show_compute_ips=x
```
as it is a extra overhead, apart from normal listing, so users whoever require IPs can add this to their config additionally.
